### ISSUE TITLE
Doc for CLI usage

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/commitlint#29]
Currently, there is no documentation regarding the CLI. Let's add it to the `README.md`.

Here are some details for the CLI. Let's use them and write standard documentation after the `For github-actions` section of `How to use`.

```
$ commitlint --help
usage: commitlint [-h] [-V] [--file FILE] [--hash HASH] [--from-hash FROM_HASH] [--to-hash TO_HASH] [--skip-detail] [commit_message]

Check if a commit message follows the conventional commit format.

positional arguments:
  commit_message        The commit message to be checked.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
  --file FILE           Path to a file containing the commit message.
  --hash HASH           Commit hash
  --from-hash FROM_HASH
                        From commit hash
  --to-hash TO_HASH     To commit hash
  --skip-detail         Skip the detailed error message check
```

### Example usage:
Check commit message directly:
```bash
$ commitlint "chore: my commit message"
```

Check commit message from file:
```bash
$ commitlint --file /foo/bar/commit-message.txt
```

Check commit message of a hash:
```bash
$ commitlint --hash 9a8c08173
```

Check commit message of a hash range:
```bash
$ commitlint --from-hash 00bf73fef7 --to-hash d6301f1eb0
```

Check commit message skipping the detail check:
```bash
$ commitlint --skip-detail "chore: my commit message"
# or
$ commitlint --skip-detail --hash 9a8c08173
```
Display help
```bash
$ commitlint --help
# or
$ commitlint -h
```
Displaying version
```bash
$ commitlint --version
# or
$ commitlint -V
```

**Comment by martincarapia** [comment]
What's a CLI? I'd love to add it to the readme but I don't know what it is.

**Comment by aj3sh** [comment]
Hello @martincarapia, our tool `commitlint` can be utilized as a Command Line Interface (CLI), and currently, we don't have proper documentation for its usage. I will be adding a detailed description of the CLI.

**Comment by martincarapia** [comment]
Oh alright. Thank you for the explanation!

**Comment by aj3sh** [comment]
I have updated the description :-)

**Comment by martincarapia** [comment]
Awesome, I'll get started.
