### ISSUE TITLE
Commit message starting with # is displayed as an empty commit

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/commitlint#49]
**Describe the bug**
Commit message starting with # is ignored and is displayed as an empty commit.

**To Reproduce**
Create a commit starting with '#'.
Eg: "#24 fixed github issue"

```bash
commitlint "#24 fixed github issue"
```

**Expected behavior**
'#' of the 1st line (commit header) should not be ignored as a comment.

**Environment**

-   Python version: N/A
-   Package version: v1
-   Operating system: Linux
-   Any other relevant information about your environment.

**Additional context**
Commitlint output
```bash
$ commitlint "#24 fixed github issue"
⧗ Input:


✖ Found 1 error(s).
- Commit message does not follow the Conventional Commits format.
```

**Comment by aj3sh** [comment]
## Additional Findings for the Bug.
- Git doesn't allow commits starting with `#` in editor mode.
- Git commit message can contain comments on the 1st line. 

Reference video:
https://github.com/opensource-nepal/commitlint/assets/35629644/25ae5390-4cfa-45b8-98cd-2ea91781fc27

## Possible Solution
Since the bug is for displaying an empty value on input, let's display whatever the commit message is (including the comments) on the **input** section.

cc: @sugat009

**Comment by sugat009** [comment]
Let's keep this issue open for now, there might be ways to work around this in the future.
